### ISSUE TITLE
Integrate into rss-bridge

### ISSUE THREAD

**Issue by josch** [daemionfox/patreon-feed#6]
Hi,

https://github.com/RSS-Bridge/rss-bridge is a php based web service offering RSS feeds for over 200 websites that do not offer one yet. But Patreon is missing. Maybe you would consider submitting a pull request to Rss-Bridge and continuing to maintain your code there?

Thanks!

cheers, josch

**Comment by daemionfox** [comment]
You are welcome to fork and integrate as long as you follow the rules of the MIT license.
